# Generated by Django 6.0.3 on 2026-04-23 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicines',
            name='custom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medicines.customer'),
            preserve_default=False,
        ),
    ]
