# Generated by Django 6.0.3 on 2026-04-23 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_alter_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='custom',
        ),
    ]
