# Generated by Django 6.0.3 on 2026-04-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_rename_name_customer_custom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='CustomerMedicine',
        ),
        migrations.RenameField(
            model_name='customermedicine',
            old_name='custom',
            new_name='custom_name',
        ),
    ]
