# Generated by Django 6.0.3 on 2026-04-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0005_rename_customer_customermedicine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicines',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
