# Generated by Django 6.0.3 on 2026-05-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0006_medicines_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicines',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='category',
            field=models.CharField(choices=[('all', 'All'), ('young', 'Young'), ('teenagers', 'Teenagers'), ('adults', 'Adults')], max_length=25),
        ),
    ]
