# Generated by Django 6.0.3 on 2026-05-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0007_medicines_embedding_alter_medicines_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
